#%RAML 1.0
title: sys-e-counselling
version: v1
baseUri: sys-e-counselling/{version}
mediaType: application/json
protocols: [https,http]
traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    responses:
      401:
        description: Unauthorized or invalid client application credentials
      500:
        description: Bad response from authorization server, or WSDL SOAP Fault error

/getCollegeCutoff:
  post:
    is : [client-id-required]
    body:
      application/json:
        example: !include examples/getCollegeCutoffRequest.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/getCollegeCutoffResponse.json
          
/getCollegeSeat:
  post:
    is : [client-id-required]
    body:
      application/json:
        example: !include examples/getCollegeSeatRequest.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/getCollegeSeatResponse-Post.json
      
  put:
    is : [client-id-required]
    body:
      application/json:
        example: !include examples/getCollegeSeatRequest.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/getCollegeSeatResponse-Put.json
              
  
/getPerformanceDetails:
  post:
    is : [client-id-required]
    body:
      application/json:
        example: !include examples/getPerformanceDetailsRequest.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/getPerformanceDetailsResponse.json
  put:
    is : [client-id-required]
    body:
      application/json:
        example: !include examples/getPerformanceDetailsRequest.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/getPerformanceDetailsResponse-put.json     
/ping:
  get:
    description: Health check endpoint for exp-e-counselling
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            example: !include examples/pingResponse.json


